parameters:
  dependsOnPublishStages: []

stages:

# Stages-based publishing entry point
- template: /eng/common/templates/post-build/post-build.yml
  parameters:
    dependsOn:
    - ${{ each dependency in parameters.dependsOnPublishStages }}:
      - CustomPublishBlob_${{ dependency.dependsOn }}
    # Symbol validation is not ready yet. https://github.com/dotnet/arcade/issues/2871
    enableSymbolValidation: false
    # Doesn't work yet, not fully configured. https://github.com/dotnet/core-setup/issues/5254
    enableSigningValidation: false
    # SourceLink validation doesn't work in dev builds: tries to pull from GitHub. https://github.com/dotnet/arcade/issues/3604
    enableSourceLinkValidation: false
    # Allow symbol publish to emit expected warnings without failing the build. Include single
    # quotes inside the string so that it passes through to MSBuild without script interference.
    symbolPublishingAdditionalParameters: "'-warnAsError:$false'"

# Create extra stages, per BAR channel that needs some extra publish steps.
- ${{ each dependency in parameters.dependsOnPublishStages }}:
  - stage: CustomPublishBlob_${{ dependency.dependsOn }}
    displayName: '${{ dependency.channel.name }} blob Publish'
    dependsOn: PrepareForPublish
    variables:
    - template: /eng/common/templates/post-build/common-variables.yml
    jobs:
    - template: /eng/jobs/custom-publish-project.yml
      parameters:
        projectName: custom-publish-blobs
        dependency: ${{ dependency }}

  - stage: CustomPublishFinal_${{ dependency.dependsOn }}
    displayName: '${{ dependency.channel.name }} Finalize'
    dependsOn:
    - ${{ dependency.dependsOn }}
    variables:
    - template: /eng/common/templates/post-build/common-variables.yml
    jobs:
    - template: /eng/jobs/custom-publish-project.yml
      parameters:
        projectName: custom-publish-final
        dependency: ${{ dependency }}
