parameters:
  Jobs: []

jobs:
- ${{ each job in parameters.Jobs }}: 
  - job: ${{ job.displayName }}
    displayName: ${{ job.displayName }}
    pool: ${{ job.pool }}
    strategy: ${{ job.strategy }}
    variables: 
      ${{ insert }}: ${{ job.variables }}

      CommonMSBuildArgs: /flp:v=diag /clp:v=detailed 
        /p:TargetArchitecture=x64
        /p:PortableBuild=false
        /p:ConfigurationGroup=$(_BuildConfiguration)
        /p:OSGroup=Linux
        /p:OfficialBuildId=$(OfficialBuildId)
        /p:StabilizePackageVersion=$(IsStable)

      SourcesDirectory: '$(Build.SourcesDirectory)'

      # Packaging related variables
      # Debian
      CommonDebianRunCommand: run --rm --name centos-7-d485f41-20173404063424ubuntu-14.04-debpkg-e5cf912-20175003025046 
        -v $(SourcesDirectory):/root/coresetup
        -v $(Build.StagingDirectory)/sharedFrameworkPublish/:/root/sharedFrameworkPublish/
        -w=/root/coresetup
        microsoft/dotnet-buildtools-prereqs:ubuntu-14.04-debpkg-e5cf912-20175003025046
        /root/coresetup/Tools/msbuild.sh
      DebianPackagingCommand: $(CommonDebianRunCommand)
        /root/coresetup/src/pkg/packaging/dir.proj
        /p:UsePrebuiltPortableBinariesForInstallers=true
        /p:SharedFrameworkPublishDir=/root/sharedFrameworkPublish/
        $(CommonMSBuildArgs)

      # RPM
      CommonRpmRunCommand: run --rm --name centos-7-d485f41-20173404063424rhel-7-rpmpkg-c982313-20174116044113
        -v $(SourcesDirectory):/root/coresetup
        -v $(Build.StagingDirectory)/sharedFrameworkPublish/:/root/sharedFrameworkPublish/
        -w=/root/coresetup
        microsoft/dotnet-buildtools-prereqs:rhel-7-rpmpkg-c982313-20174116044113
        /root/coresetup/Tools/msbuild.sh
      RpmPackagingCommand: $(CommonRpmRunCommand)
        /root/coresetup/src/pkg/packaging/dir.proj
        /p:UsePrebuiltPortableBinariesForInstallers=true
        /p:SharedFrameworkPublishDir=/root/sharedFrameworkPublish/
        $(CommonMSBuildArgs)
    steps:

    # Build binary and nuget packages
    - script: $(RunArguments)
        ./build.sh
        $(BuildArguments)
      displayName: Build
      workingDirectory: '$(SourcesDirectory)'

    # Publish only if internal and not PR 
    - ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
      - script: $(RunArguments)
          ./Tools/msbuild.sh
          ./publish/publish.proj
          $(PublishArguments)
          $(_CommonPublishArgs)
        displayName: Publish
        workingDirectory: '$(SourcesDirectory)'
        condition: and(succeeded(), eq(variables._BuildConfiguration, 'Release'))

    # Only for glibc leg, here we produce RPMs and Debs
    - ${{ if eq(job.displayName,'Linux_x64_glibc')}}:
      - task: CopyFiles@2
        displayName: 'Copy built Portable linux-x64 binaries to staging directory'
        inputs:
          SourceFolder: '$(SourcesDirectory)/bin/obj/linux-x64.$(_BuildConfiguration)/sharedFrameworkPublish'
          TargetFolder: '$(Build.StagingDirectory)/sharedFrameworkPublish'
      - script: docker 
          $(CommonDebianRunCommand)
          /root/coresetup/build.proj
          /t:BuildTraversalBuildDependencies
          $(CommonMSBuildArgs)
        displayName: Build traversal build dependencies - Ubuntu 14.04
        workingDirectory: '$(SourcesDirectory)'

      # Debian packaging
      - script: docker 
          $(DebianPackagingCommand)
        displayName: 'Package Runtime packages and Runtime Dep - Ubuntu 14.04'
        workingDirectory: '$(SourcesDirectory)'

      - ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
        - script: docker
            $(CommonDebianRunCommand)
            /root/coresetup/publish/publish.proj
            /p:PublishType=$(PublishType)
            /p:SharedFrameworkPublishDir=/root/sharedFrameworkPublish/
            $(CommonMSBuildArgs) 
            $(_CommonPublishArgs)
          displayName: 'Publish Runtime and Runtime Dep - Ubuntu 14.04'
          workingDirectory: '$(SourcesDirectory)'
          condition: and(succeeded(), eq(variables._BuildConfiguration, 'Release'))

      # Package and publish for each debian distros
      - ${{ each debdistrorid in job.packageDistroListDeb }}:
        - script: docker
            $(DebianPackagingCommand) /p:BuildRuntimeDebs=false
            /p:OutputRid=${{ debdistrorid }}-$(_TargetArchitecture)
          displayName: 'Package Runtime Dep - ${{ debdistrorid }}'
        - ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
          - script: docker
              $(CommonDebianRunCommand)
              /root/coresetup/publish/publish.proj
              /p:PublishType=$(PublishType)
              /p:SharedFrameworkPublishDir=/root/sharedFrameworkPublish/ 
              $(CommonMSBuildArgs)
              $(_CommonPublishArgs)
              /p:OutputRid=${{ debdistrorid }}-$(_TargetArchitecture)
            displayName: 'Publish Runtime Dep - ${{ debdistrorid }}'
            workingDirectory: '$(SourcesDirectory)'
            condition: and(succeeded(), eq(variables._BuildConfiguration, 'Release'))

      # RPM Packaging
      - script: docker
          $(CommonRpmRunCommand)
          /root/coresetup/build.proj
          /t:BuildTraversalBuildDependencies
          $(CommonMSBuildArgs) 
        displayName: Build traversal build dependencies - Rhel7
        workingDirectory: '$(SourcesDirectory)'
      - script: docker 
          $(RpmPackagingCommand)
        displayName: Package Runtime Dep - Rhel7
      - ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
        - script: docker 
            $(CommonRpmRunCommand) 
            /root/coresetup/publish/publish.proj
            /p:PublishType=$(PublishType)
            /p:SharedFrameworkPublishDir=/root/sharedFrameworkPublish/
            $(CommonMSBuildArgs)
            $(_CommonPublishArgs)
          displayName: Publish Runtime Dep - Rhel7
          workingDirectory: '$(SourcesDirectory)'
          condition: and(succeeded(), eq(variables._BuildConfiguration, 'Release'))

      # Package and publish for each rpm distros
      - ${{ each rpmdistrorid in job.packageDistroListRpm }}: 
        - script: docker 
            $(RpmPackagingCommand) /p:BuildRuntimeRpms=false
            /p:OutputRid=${{ rpmdistrorid }}-$(_TargetArchitecture)
          displayName: 'Package Runtime Dep - ${{ rpmdistrorid }}'
        - ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
          - script: docker
              $(CommonRpmRunCommand)
              /root/coresetup/publish/publish.proj
              /p:PublishType=$(PublishType)
              /p:SharedFrameworkPublishDir=/root/sharedFrameworkPublish/
              $(CommonMSBuildArgs)
              $(_CommonPublishArgs)
              /p:OutputRid=${{ rpmdistrorid }}-$(_TargetArchitecture)
            displayName: 'Publish Runtime Dep -${{ rpmdistrorid }}'
            workingDirectory: '$(SourcesDirectory)'
            condition: and(succeeded(), eq(variables._BuildConfiguration, 'Release'))
    - task: CopyFiles@2
      displayName: Copy Files to $(Build.StagingDirectory)\BuildLogs
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)'
        Contents: |
          *.log
          *.binlog
        TargetFolder: '$(Build.StagingDirectory)\BuildLogs'
      continueOnError: true
      condition: succeededOrFailed()
    - task: PublishBuildArtifacts@1
      displayName: Publish Artifact BuildLogs
      inputs:
        PathtoPublish: '$(Build.StagingDirectory)\BuildLogs'
        ArtifactName: ${{ job.displayName }}-$(_BuildConfiguration)
      continueOnError: true
      condition: succeededOrFailed()