name: dotnet-runtime-30
version: 3.0.0
summary: Cross-Platform .NET Core Runtime. 
description: |
  .NET Core 3.0 Runtime and ASP.NET Core. https://dot.net/core.

grade: stable
confinement: strict

apps:
  dotnet:
    command: dotnet
    plugs:
      - network
      - network-bind
      - removable-media
      - home

base: core18

slots:
  dotnet-runtime:
    content: dotnet-runtime-30
    interface: content
    read: [/]

parts:
  dotnet-runtime:
    plugin: dump
    source: https://download.visualstudio.microsoft.com/download/pr/a5ff9cbb-d558-49d1-9fd2-410cb1c8b095/a940644f4133b81446cb3733a620983a/dotnet-runtime-3.0.0-linux-x64.tar.gz
    source-checksum: sha512/0cabf85877eb3ee0415e6f8de9390c95ec90fa8f5a0fdb104f1163924fd52d89932a51c2e07b5c13a6b9802d5b6962676042a586ec8aff4f2a641d33c6c84dec
    stage-packages:
      - libicu60
      - libssl1.0.0
      - libcurl3
      - libgssapi-krb5-2
      - liblttng-ust0
      - libstdc++6
      - zlib1g
      - libgcc1
      - lldb
      - libunwind8
      - libtinfo5
      - libdb5.3
      - libc6