name: dotnet-sdk
version: 2.1.607
summary: Cross-Platform .NET Core SDK
description: |
  .NET Core SDK. https://dot.net/core.

grade: stable
confinement: classic

apps:
  dotnet:
    command: dotnet

base: core18

parts:
  dotnet-sdk:
      plugin: dump
      source: https://download.visualstudio.microsoft.com/download/pr/39e68289-0364-4173-a12b-c6234e94c527/92f3eb83bfca8b7cd360868996763125/dotnet-sdk-2.1.607-linux-x64.tar.gz
      source-checksum: sha512/bfcee5d0121bc3b4dcd08c7a99e700a9dc89e9dcf326ae40046a222bc2fe0212bca14811dcf1e96a6cc6ecd085fbc492e30dc2c2d19ee1741960bbd5e238233a
      stage-packages:
        - libicu60
        - libssl1.0.0
        - libcurl3
        - libgssapi-krb5-2
        - libstdc++6
        - zlib1g
        - libgcc1
        - lldb
        - libunwind8
        - libtinfo5
        - liblttng-ust0
        - liburcu6

  runtime-wrapper:
      plugin: dump
      source: .

